// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrincessProject.Data.context;

#nullable disable

namespace PrincessProject.Data.Migrations
{
    [DbContext(typeof(AttemptContext))]
    [Migration("20221004144234_Updates")]
    partial class Updates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("PrincessProject.Data.model.AttemptDataDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CandidateSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidateValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.ToTable("AttemptData");
                });

            modelBuilder.Entity("PrincessProject.Data.model.AttemptDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("ChosenValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("PrincessProject.Data.model.AttemptDataDto", b =>
                {
                    b.HasOne("PrincessProject.Data.model.AttemptDto", "AttemptDto")
                        .WithMany("AttemptDataDtos")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttemptDto");
                });

            modelBuilder.Entity("PrincessProject.Data.model.AttemptDto", b =>
                {
                    b.Navigation("AttemptDataDtos");
                });
#pragma warning restore 612, 618
        }
    }
}
