// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrincessProject.Data.context;

#nullable disable

namespace PrincessProject.Data.Migrations
{
    [DbContext(typeof(AttemptContext))]
    [Migration("20221004135345_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("PrincessProject.Data.model.AttemptDataDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("id"));

                    b.Property<int>("attempt_id")
                        .HasColumnType("integer");

                    b.Property<string>("candidate_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("candidate_surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("candidate_value")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("AttemptData");
                });

            modelBuilder.Entity("PrincessProject.Data.model.AttemptDto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("id"));

                    b.Property<int>("happiness")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
