// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrincessProject.Data.context;

#nullable disable

namespace PrincessProject.Data.Migrations
{
    [DbContext(typeof(AttemptContext))]
    partial class AttemptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("PrincessProject.Data.model.AttemptDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidateOrder")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidateValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AttemptData");
                });
#pragma warning restore 612, 618
        }
    }
}
