using PrincessProject.model;

namespace PrincessProject.Hall;

/*
 * Defines hall, which is able to generate and give away contenders
 */
public interface IHall
{
    /*
     * Method, which returns number of candidates generated by hall
     */
    int GetTotalCandidates();
    /*
     * Method, which gives away next contender
     */
    ContenderName GetNextContender();
    /*
     * Method, which compares contenders
     */
    ContenderName CompareContenders(ContenderName first, ContenderName second);
}